# Numpy Practice

In [1]:
import numpy as np
import math

# Array Creation

In [2]:
a = np.array([1, 2, 3])
print(a)

print(a.ndim)

[1 2 3]
1


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int64')

In [7]:
c = np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [8]:
c

array([2.2, 5. , 1.1])

In [13]:
d = np.zeros((2, 3))
print(d)

e = np.ones((2, 3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
np.random.rand(2, 3)

array([[0.68716516, 0.95510686, 0.15625593],
       [0.77868336, 0.55222201, 0.26214397]])

In [16]:
f = np.arange(10, 50, 2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [17]:
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Array Operations

In [18]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

c = a - b
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [19]:
fahrenheit = np.array([0, -10, -5, -15, 0])

celsius = (fahrenheit - 31) * 5/9
celsius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [20]:
celsius > -20

array([ True, False, False, False,  True])

In [21]:
celsius % 2 == 0

array([False, False,  True, False, False])

In [30]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print(A)
print(B)
print(A*B)
print(A@B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [24]:
A.shape

(2, 2)

In [26]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1.dtype)

array2 = np.array([[7.1, 8.2, 9.1], [10.4, 11.2, 12.3]])
print(array2.dtype)

int64
float64


In [27]:
array3 = array1 + array2
print(array3)
print(array3.dtype)

[[ 8.1 10.2 12.1]
 [14.4 16.2 18.3]]
float64


In [28]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

79.3
18.3
8.1
13.216666666666667


In [29]:
b = np.arange(1, 16, 1).reshape(3, 5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
